### ISSUE TITLE
a requirements.txt file is needed to keep dependencies

### ISSUE THREAD

**Issue by emieza** [NotAlba/djmatrics#3]
al python packages managed with pip can be seen with `pip freeze`

you should create a requirements.txt file by doing `pip freeze > requirements.txt` and keep it into the project root in order to automate the deploy system

Remember to add it to repo and keep it up to date.

to load dependencies you just do: `pip install -r requirements.txt`

**Comment by rbnmf** [comment]
Added, see https://github.com/NotAlba/djmatrics/commit/dc3c5140c9df7a7ace3ab803bdae4f331fe3df86
